"""
train/compare_heldout_cities.py — per-city, model-vs-model comparison on the
cities each model never saw.

Why this exists: the 10 OSCD test cities carry no ground truth (see
`data/splits.py`, `TEST_CITIES`: predict-only), so no metric can be computed on
them locally. The only labelled cross-city evidence is the 5-fold *city-grouped*
CV over the 14 labelled cities: every city is held out exactly once, and the
model that scores it was trained without it. That is a leave-city-out
comparison, not an in-sample one — it answers "which circuit generalizes to an
unseen city" with 14 held-out cities instead of 10.

The comparison is *paired*: all cells share one fold assignment
(`splits.get_grouped_folds(5, seed=0)`), one init seed and one patch stream, so
city `c` is scored by every model under identical conditions. Per-city
differences are therefore matched pairs and win counts are meaningful.

Reads only committed artifacts (`results/runs/p3_topology/*.json`) — no dataset,
no GPU, no retraining. Writes a CSV of every (model, city) cell and a markdown
report.

    python train/compare_heldout_cities.py                 # all depths
    python train/compare_heldout_cities.py --depth 3       # one depth
    python train/compare_heldout_cities.py --metric F1
"""
import os, sys, json, glob, argparse
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, "data"))

from splits import TRAIN_CITIES

SWEEP = os.path.join(ROOT, "results", "runs", "p3_topology")
KINDS = ["m1", "m2", "mring"]
LABEL = {"m1": "M1 separable", "m2": "M2 spatial CZ grid", "mring": "M_ring CZ ring"}
METRICS = ["AP", "roc_auc", "F1", "precision", "change_acc", "nochange_acc", "accuracy"]


# --------------------------------------------------------------------------- #
def load_cells(sweep=SWEEP):
    """{(kind, depth): {city: metrics}} plus {(kind, depth): {city: fold}}."""
    cells, folds = {}, {}
    for path in sorted(glob.glob(os.path.join(sweep, "*_fold*.json"))):
        r = json.load(open(path))
        key = (r["kind"], r["depth"])
        cells.setdefault(key, {})
        folds.setdefault(key, {})
        for city, m in r["per_city"].items():
            if city in cells[key]:
                raise ValueError(f"{city} appears twice for {key} — folds overlap?")
            cells[key][city] = m
            folds[key][city] = r["fold"]
    return cells, folds


def check_coverage(cells):
    """Every model must cover all 14 labelled cities exactly once, or the macro
    means are not comparable. Reported, never silently patched."""
    problems = []
    for key, per_city in sorted(cells.items()):
        missing = [c for c in TRAIN_CITIES if c not in per_city]
        extra = [c for c in per_city if c not in TRAIN_CITIES]
        if missing or extra:
            problems.append((key, missing, extra))
    return problems


def paired_table(cells, kind_a, kind_b, depth, metric):
    """Matched per-city values for two models at one depth."""
    A, B = cells.get((kind_a, depth)), cells.get((kind_b, depth))
    if not A or not B:
        return None
    rows = []
    for c in TRAIN_CITIES:
        if c in A and c in B:
            rows.append({"city": c, "prevalence": A[c]["prevalence"],
                         "a": A[c][metric], "b": B[c][metric],
                         "d": A[c][metric] - B[c][metric]})
    return rows


def fmt(x, n=4):
    return "n/a" if x is None or (isinstance(x, float) and np.isnan(x)) else f"{x:.{n}f}"


# --------------------------------------------------------------------------- #
def write_csv(cells, folds, path):
    import csv
    with open(path, "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["kind", "depth", "fold", "city", "n", "prevalence"] + METRICS)
        for (kind, depth), per_city in sorted(cells.items()):
            for city in TRAIN_CITIES:
                if city not in per_city:
                    continue
                m = per_city[city]
                w.writerow([kind, depth, folds[(kind, depth)][city], city,
                            m["n"], f"{m['prevalence']:.6f}"]
                           + [f"{m[k]:.6f}" for k in METRICS])
    return path


def write_report(cells, folds, depths, metric, path):
    out = []
    A = out.append
    A("# Held-out-city model comparison\n")
    A("Generated by [`train/compare_heldout_cities.py`](../train/compare_heldout_cities.py) "
      "from the committed fold results in `results/runs/p3_topology/`.\n")
    A("## What is being compared, and on which cities\n")
    A("The 10 OSCD **test** cities have no ground truth (`data/splits.py` — "
      "`TEST_CITIES`, predict-only), so no accuracy number can be computed on them "
      "here; the deliverable for those is a predicted mask per city. Every metric "
      "below is on a **held-out city**: 5-fold city-grouped CV over the 14 labelled "
      "cities, each city held out exactly once and scored by a model trained "
      "without it.\n")
    A("The comparison is paired — identical fold assignment, identical "
      "initialisation and identical training patch stream across models, so the "
      "circuit is the only difference and per-city differences are matched pairs.\n")
    A(f"Primary metric here: **{metric}**. Chance level for AP is the city's own "
      "prevalence (~2.3 % overall), so AP values must be read against that column.\n")

    for depth in depths:
        present = [k for k in KINDS if (k, depth) in cells]
        if not present:
            continue
        n_params = {k: json.load(open(glob.glob(os.path.join(
            SWEEP, f"{k}_L{depth}_fold*.json"))[0]))["n_params"] for k in present}
        A(f"\n## Depth L{depth} — {n_params[present[0]]} parameters\n")

        head = "| city | fold | prevalence | " + " | ".join(LABEL[k] for k in present) + " |"
        A(head)
        A("|" + "---|" * (3 + len(present)))
        for city in TRAIN_CITIES:
            vals = [cells[(k, depth)].get(city, {}).get(metric) for k in present]
            f = folds[(present[0], depth)].get(city, "?")
            prev = cells[(present[0], depth)].get(city, {}).get("prevalence")
            best = max([v for v in vals if v is not None], default=None)
            cell = " | ".join(f"**{fmt(v)}**" if v == best else fmt(v) for v in vals)
            A(f"| {city} | {f} | {fmt(prev, 4)} | {cell} |")
        macro = [np.mean([cells[(k, depth)][c][metric] for c in TRAIN_CITIES
                          if c in cells[(k, depth)]]) for k in present]
        A(f"| **macro (14 cities)** |  |  | " +
          " | ".join(f"**{fmt(v)}**" if v == max(macro) else fmt(v) for v in macro) + " |")

        A("\n**Paired differences vs M1** (positive = M1 better):\n")
        A("| comparison | mean Δ | median Δ | M1 wins | cities where the other wins |")
        A("|---|---|---|---|---|")
        for k in present:
            if k == "m1":
                continue
            rows = paired_table(cells, "m1", k, depth, metric)
            if not rows:
                continue
            d = np.array([r["d"] for r in rows])
            losers = [r["city"] for r in rows if r["d"] < 0]
            A(f"| M1 − {LABEL[k]} | {fmt(d.mean())} | {fmt(float(np.median(d)))} | "
              f"{int((d > 0).sum())}/{len(d)} | {', '.join(losers) if losers else '—'} |")

        spread = [cells[(present[0], depth)][c][metric] for c in TRAIN_CITIES
                  if c in cells[(present[0], depth)]]
        A(f"\nCity spread for {LABEL[present[0]]}: {fmt(min(spread))} … {fmt(max(spread))} "
          f"({max(spread) / max(min(spread), 1e-9):.1f}×) — compare that against the "
          "mean paired differences above.\n")

    A("\n## Reading guide\n")
    A("- **Per-city win counts are the honest unit here, not the macro mean.** 14 "
      "cities come from 5 trained models per cell, so cities inside a fold share a "
      "model and are not independent samples. No p-values are computed.\n")
    A("- F1 in the per-city tables uses a **per-city** threshold swept on the very "
      "pixels it scores — an optimistic best-operating-point diagnostic, not a "
      "deployment number. The deployment operating point is the single frozen "
      "τ\\* = 0.5808 from pooled out-of-fold predictions.\n")
    A("- A model winning on macro AP while losing on several cities is a domain-shift "
      "result, not an architecture result. Finding 3 in the poster says exactly this.\n")

    open(path, "w").write("\n".join(out) + "\n")
    return path


# --------------------------------------------------------------------------- #
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sweep", default=SWEEP)
    ap.add_argument("--depth", type=int, default=None, help="default: every depth found")
    ap.add_argument("--metric", default="AP", choices=METRICS)
    ap.add_argument("--csv", default=os.path.join(ROOT, "results", "p3_matrix",
                                                  "per_city_heldout.csv"))
    ap.add_argument("--report", default=os.path.join(ROOT, "docs",
                                                     "results_heldout_city_comparison.md"))
    a = ap.parse_args()

    cells, folds = load_cells(a.sweep)
    if not cells:
        sys.exit(f"no fold results under {a.sweep}")
    problems = check_coverage(cells)
    for key, missing, extra in problems:
        print(f"  WARNING {key}: missing {missing} extra {extra}")

    depths = [a.depth] if a.depth else sorted({d for _, d in cells})
    write_csv(cells, folds, a.csv)
    write_report(cells, folds, depths, a.metric, a.report)

    print(f"{len(cells)} cells, {sum(len(v) for v in cells.values())} (model, city) rows")
    for depth in depths:
        present = [k for k in KINDS if (k, depth) in cells]
        for k in present:
            v = [cells[(k, depth)][c][a.metric] for c in TRAIN_CITIES if c in cells[(k, depth)]]
            print(f"  L{depth} {k:6} macro {a.metric} {np.mean(v):.4f}  "
                  f"(min {min(v):.4f} max {max(v):.4f}, {len(v)} held-out cities)")
    print(f"-> {a.csv}\n-> {a.report}")


if __name__ == "__main__":
    main()
